title = "Async Rust"
author = "cognitive-engineering-lab"
repo = "rqst-async"

[[stages]]
label = "00-chat-route"
name = "Warmup"

[[stages]]
label = "01-async-await"
name = "Async and Await"

[[stages]]
label = "02-join"
name = "The join! macro"

[[stages]]
label = "03-spawn"
name = "Spawning tasks"