title = "Async Rust"
author = "cognitive-engineering-lab"
repo = "rqst-async"

[[stages]]
label = "00-chat-route"
name = "Warmup"
no-starter = true

[[stages]]
label = "01-async-await"
name = "Async and Await"

[[stages]]
label = "02-join"
name = "Joining Futures"

[[stages]]
label = "03-spawn"
name = "Spawning Tasks"

[[stages]]
label = "04-message-passing"
name = "Message Passing"

[[stages]]
label = "05-many-futures"
name = "Waiting on Many Futures"