[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
miniserve = { path = "../miniserve" }
chatbot = { path = "../chatbot" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
tokio = { workspace = true, features = ["full"] }
