name: CI

on:
  push:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: cargo test
      - name: Lints
        run: cargo clippy -- -D warnings