name: CI
on:
  push:
  workflow_dispatch:

jobs:
  create-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install RepoQuest
        uses: baptiste0928/cargo-install@v3.4.0
        with:
          crate: repo-quest
          git: https://github.com/cognitive-engineering-lab/repo-quest.git
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test quest
        run: repo-quest test
      - name: Bundle quest
        run: RUST_LOG=debug repo-quest bundle --output rqst-async.tgz
      - uses: actions/upload-artifact@v6
        with:
          name: rqst-async
          path: rqst-async.tgz
