name: CI
on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install RepoQuest
        uses: baptiste0928/cargo-install@v3.4.0
        with:
          crate: repo-quest
          git: https://github.com/cognitive-engineering-lab/repo-quest.git
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test quest
        run: repo-quest test
      - name: Bundle quest
        run: RUST_LOG=debug repo-quest bundle --output rqst-async.tgz
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: rqst-async.tgz
