name: CI

on:
  push:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Toolchain
        run: rustup toolchain install stable
      - name: Build cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
      - name: Lints
        run: cargo clippy -- -D warnings